### PR TITLE
Add: This commit creates a github actions file which will execute build

### PR DESCRIPTION
**Pull request by poetaster**
and release when a tag beginning with v is commited. It uses @coderus docker images.

### CODE REVIEW

**Comment by poetaster** [comment]
The rest of my work is in other branches.

**Comment by rabauke** [comment]
The addition of a git workflow is highly appreciated. 

Regarding the UI changes, though, I think they do not comply with the Sailfish OS design principles, which favours gestures over buttons.  Furthermore, the added help-button covers too much screen estate and appears distracting to me.

Nevertheless, your UI changes address an actual shortcoming of the current UI: The documentation for the available mathematical functions is not easy to access.  Users might not expect to find this under the "About Babbage".

As an alternative to your UI changes I would suggest to add an additional PushUpMenu with a single menu item to open the "List of function". (One might consider, adding this menu item to the existing PullDownMenu, though I think it is good practice to keep the number of menu items per menu small.)  The push-up-menu approach would be more consistent with the Sailfish OS design principles.

**Comment by poetaster** [comment]
> As an alternative to your UI changes I would suggest to add an additional PushUpMenu with a single menu item to open the "List of function". (One might consider, adding this menu item to the existing PullDownMenu, though I think it is good practice to keep the number of menu items per menu small.) The push-up-menu approach would be more consistent with the Sailfish OS design principles.

That's a reasonable suggestion. For the Exprtk interfaces, however, I would prefer to have the short cut handy since it it, simply, reasonable to hit the button than invoke a gesture. It's much more efficient. I have, on my https://github.com/poetaster/harbour-babbage/tree/document branch also implemented copy from your FunctionDoc type, but it's a hack. In my documentation, I'm using a listivew with context menu which is cleaner, but I was unable to make work for FunctionDoc.

I'm going to PR the document branch now to see what you think. I suspect there will probably be too many diverging interests, philosophical disputes, but babbage was all we had to date. Thanks!

**Comment by poetaster** [comment]
Just a note, I've tested the github action (using: git tag v0.19,  git push origin --tags) and it's clean. tested aarch64 and arm.
https://github.com/poetaster/harbour-babbage/releases if you wish you can see the exprtk work from that install.

**Pull request merged**
